# Generated by Django 3.2.5 on 2021-07-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
    ]
