# Generated by Django 3.2.5 on 2021-07-23 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20210722_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='discription',
            new_name='description',
        ),
    ]
