# Generated by Django 3.2.5 on 2021-07-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_rename_discription_notes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
